//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingVL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ID { get; set; }
        public string User_ID { get; set; }
        public int Meeting_ID { get; set; }
        public string Work { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Description { get; set; }
    
        public virtual MeetingMinute MeetingMinute { get; set; }
        public virtual User User { get; set; }
    }
}
