//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingVL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evaluate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluate()
        {
            this.Comments = new HashSet<Comment>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "No user_id yet!")]
        public string User_ID { get; set; }
        [Required(ErrorMessage = "No Group_id yet!")]
        public int Group_ID { get; set; }
        public Nullable<int> Semester_ID { get; set; }
        [StringLength(200, ErrorMessage = "State length must be between 1 and 100.", MinimumLength = 1)]
        public string State { get; set; }
        [Required(ErrorMessage = "You have not entered the Review")]
        public string Review { get; set; }
      
        [StringLength(50, ErrorMessage = "State length must be between 1 and 50.", MinimumLength = 1)]
        public string Status { get; set; }
        [Required(ErrorMessage = "No point yet!")]
        public Nullable<int> Point { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Group Group { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
