//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingVL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Evaluates = new HashSet<Evaluate>();
            this.MeetingMinutes = new HashSet<MeetingMinute>();
            this.ProjectParticipants = new HashSet<ProjectParticipant>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "You have not entered the name category")]
        [StringLength(250, ErrorMessage = "Name length must be between 1 and 250.", MinimumLength = 1)]
        public string Name { get; set; }
        [Required(ErrorMessage = "You have not entered the Topic")]
        [StringLength(250, ErrorMessage = "Topic length must be between 1 and 250.", MinimumLength = 1)]
        public string Topic { get; set; }
        [Required(ErrorMessage = "You have not entered the name category")]
        [StringLength(250, ErrorMessage = "Mentor length must be between 1 and 250.", MinimumLength = 1)]
        public string Mentor { get; set; }
        [StringLength(250, ErrorMessage = "Customer length must be between 1 and 250.", MinimumLength = 1)]
        public string Customer { get; set; }
        [StringLength(50, ErrorMessage = "State length must be between 1 and 50.", MinimumLength = 1)]
        public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluate> Evaluates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingMinute> MeetingMinutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectParticipant> ProjectParticipants { get; set; }
    }
}
