//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingVL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MeetingMinute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingMinute()
        {
            this.Actions = new HashSet<Action>();
        }
    
        public int ID { get; set; }
        public string User_ID { get; set; }
        public int SessionReport_ID { get; set; }
        public System.DateTime Date_start { get; set; }
        public Nullable<System.DateTime> Date_end { get; set; }
        [Required(ErrorMessage = "You have not entered the Location")]
        [StringLength(100, ErrorMessage = "Location length must be between 1 and 100.", MinimumLength = 1)]

        public string Location { get; set; }
        public string Objectives { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Issues { get; set; }
        public string NA { get; set; }
        public int Process { get; set; }
        [StringLength(200, ErrorMessage = "Stages length must be between 1 and 200.", MinimumLength = 1)]

        public string Stages { get; set; }
        public Nullable<int> Group_ID { get; set; }
        [StringLength(50, ErrorMessage = "State length must be between 1 and 50.", MinimumLength = 1)]

        public string State { get; set; }
        public string Member { get; set; }
        public string Mentor { get; set; }
        public string Customer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        public virtual Group Group { get; set; }
        public virtual SessionReport SessionReport { get; set; }
        public virtual User User { get; set; }
    }
}
