//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingVL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Actions = new HashSet<Action>();
            this.Categories = new HashSet<Category>();
            this.Comments = new HashSet<Comment>();
            this.Evaluates = new HashSet<Evaluate>();
            this.MeetingMinutes = new HashSet<MeetingMinute>();
            this.Notifications = new HashSet<Notification>();
            this.ProjectParticipants = new HashSet<ProjectParticipant>();
            this.Semesters = new HashSet<Semester>();
        }
        [Required(ErrorMessage = "You have not entered the Email")]
        [StringLength(250, ErrorMessage = "Email length must be between 1 and 250.", MinimumLength = 1)]
        public string Email { get; set; }
        [StringLength(250, ErrorMessage = "ID_VanLang length must be between 1 and 250.", MinimumLength = 1)]
        public string ID_VanLang { get; set; }
        [StringLength(100, ErrorMessage = "Name length must be between 1 and 100.", MinimumLength = 1)]
        public string Name { get; set; }
        [StringLength(36, ErrorMessage = "Role length must be between 1 and 36.", MinimumLength = 1)]
        public string Role { get; set; }
        [StringLength(250, ErrorMessage = "Token length must be between 1 and 250.", MinimumLength = 1)]
        public string Token { get; set; }
        public Nullable<System.DateTime> Last_Access { get; set; }
        [StringLength(100, ErrorMessage = "Department length must be between 1 and 100.", MinimumLength = 1)]
        public string Department { get; set; }
        [StringLength(100, ErrorMessage = "Majors length must be between 1 and 100.", MinimumLength = 1)]
        public string Majors { get; set; }
        public Nullable<bool> State { get; set; }
        public string Avt { get; set; }
        public int stt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluate> Evaluates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingMinute> MeetingMinutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectParticipant> ProjectParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Semester> Semesters { get; set; }
    }
}
